# Generated by Django 3.2 on 2021-08-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraimages',
            options={'verbose_name': 'Extra Image', 'verbose_name_plural': 'Extra Images'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PHY', 'Physical'), ('VAR', 'Vartual')], default='PHY', max_length=3),
        ),
    ]
