# Generated by Django 3.2 on 2021-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210804_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PHY', 'Physical'), ('VIR', 'Virtual')], default='PHY', max_length=3),
        ),
    ]
