# Generated by Django 3.2.5 on 2021-08-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_category_thumbneil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_thumbneil',
            field=models.ImageField(blank=True, upload_to='category/thumbneil'),
        ),
    ]
